[project]
name = "researchpal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "biabcaval", email = "biabcaval@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.5.9",
    "fastapi>=0.115.0",
    "pypdf2>=3.0.1",
    "python-dotenv>=1.0.1",
    "requests>=2.34.2",
    "uvicorn[standard]>=0.34.0",
]

[project.scripts]
researchpal = "researchpal:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
